version: '3'
services:
  kapital_streamlit:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kapital-streamlit
    env_file:
      - .env-prod
    ports:
      - 8501:8501
